name: Gemini Lint Fix Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: List all files
      run: ls -R

    - name: Print Node.js version
      run: node -v

    - name: Run ESLint
      id: eslint
      run: pnpm run lint --verbose | tee eslint.log

    - name: Output ESLint Log
      run: cat eslint.log

    - name: Run Prettier
      id: prettier
      run: pnpm run prettier --verbose | tee prettier.log

    - name: Output Prettier Log
      run: cat prettier.log

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Identify Failed Files
      run: |
        echo "Identifying failed files..."
        touch failed_files.txt
        grep -oP '(?<=^).*(?= error)' eslint.log > failed_files.txt || true
        grep -oP '(?<=^).*(?= error)' prettier.log >> failed_files.txt || true
        if [ ! -s failed_files.txt ]; then
          rm failed_files.txt
        fi
        echo "Contents of failed_files.txt:"
        if [ -f failed_files.txt ]; then
          cat failed_files.txt
        else
          echo "No failed files found."

    - name: Check failed_files.txt presence and content
      run: |
        if [ -f failed_files.txt ]; then
          echo "failed_files.txt exists."
          cat failed_files.txt
        else
          echo "failed_files.txt does not exist."

    - name: Print failed_files.txt before running AI Fix Script
      run: |
        if [ -f failed_files.txt ]; then
          echo "Contents of failed_files.txt before running AI Fix Script:"
          cat failed_files.txt
        else
          echo "failed_files.txt does not exist before running AI Fix Script."

    - name: Run AI Fix Script
      run: |
        echo "Running AI Fix Script..."
        echo "Current working directory: $(pwd)"
        echo "Environment variables:"
        printenv
        node ai-fix-script.js
        if [ $? -ne 0 ]; then
          echo "AI Fix Script encountered an error."
        else
          echo "AI Fix Script completed successfully."

    - name: Parse and Comment Suggestions
      run: |
        if [ -f suggestions.txt ]; then
          cat suggestions.txt | while IFS= read -r suggestion; do
            gh pr comment ${{ github.event.pull_request.number }} --body "$suggestion"
          done
        else
          echo "No suggestions file found."

    - name: Check if Suggestions File Exists
      run: |
        if [ -f suggestions.txt ]; then
          echo "Suggestions file exists."
        else
          echo "Suggestions file does not exist."

    - name: Upload Suggestions Artifact
      uses: actions/upload-artifact@v3
      with:
        name: suggestions
        path: suggestions.txt

    - name: Check for merge conflicts in pnpm-lock.yaml
      run: |
        echo "Checking for merge conflicts in pnpm-lock.yaml..."
        if git ls-files -u | grep -q 'pnpm-lock.yaml'; then
          echo "Merge conflict detected in pnpm-lock.yaml" && echo "::set-output name=conflict::true"
        else
          echo "No merge conflict in pnpm-lock.yaml" && echo "::set-output name=conflict::false"
