name: Gemini Lint Fix Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run ESLint
      id: eslint
      run: pnpm run lint | tee eslint.log

    - name: Run Prettier
      id: prettier
      run: pnpm run prettier | tee prettier.log

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Identify Failed Files
      if: failure()
      run: |
        grep -l "error" eslint.log > failed_files.txt
        grep -l "error" prettier.log >> failed_files.txt

    - name: Run AI Fix Script
      if: failure()
      run: node ai-fix-script.js

    - name: Parse and Comment Suggestions
      if: failure()
      run: |
        cat suggestions.txt | while IFS= read -r suggestion; do
          gh pr comment ${{ github.event.pull_request.number }} --body "$suggestion"
        done

    - name: Check if Suggestions File Exists
      if: failure()
      run: |
        if [ -f suggestions.txt ]; then
          echo "Suggestions file exists."
        else
          echo "Suggestions file does not exist."
        fi

    - name: Upload Suggestions Artifact
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: suggestions
        path: suggestions.txt

# This is a test comment to create a new commit on the test-github-action branch
