name: Gemini Lint Fix Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      id: eslint
      run: npm run lint -- --format json --output-file eslint.log
      continue-on-error: true

    - name: Run Prettier
      id: prettier
      run: npm run prettier -- --loglevel debug > prettier.log
      continue-on-error: true

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Identify Failed Files
      if: failure()
      run: |
        grep -l "error" eslint.log > failed_files.txt
        grep -l "error" prettier.log >> failed_files.txt

    - name: Run AI Fix Script
      if: failure()
      run: node ai-fix-script.js

    - name: Parse and Comment Suggestions
      if: failure()
      run: |
        cat suggestions.txt | while IFS= read -r suggestion; do
          gh pr comment ${{ github.event.pull_request.number }} --body "$suggestion"
        done
