name: Gemini Lint Fix Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run ESLint
      id: eslint
      run: pnpm run lint --verbose | tee eslint.log

    - name: Output ESLint Log
      run: cat eslint.log

    - name: Run Prettier
      id: prettier
      run: pnpm run prettier --verbose | tee prettier.log

    - name: Output Prettier Log
      run: cat prettier.log

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Identify Failed Files
      run: |
        echo "Identifying failed files..."
        touch failed_files.txt
        grep -l "error" eslint.log > failed_files.txt || true
        grep -l "error" prettier.log >> failed_files.txt || true
        if [ ! -s failed_files.txt ]; then
          rm failed_files.txt
        fi
        echo "Contents of failed_files.txt:"
        if [ -f failed_files.txt ]; then
          cat failed_files.txt
        else
          echo "No failed files found."
        fi

    - name: Run AI Fix Script
      run: |
        echo "Running AI Fix Script..."
        node ai-fix-script.js

    - name: Parse and Comment Suggestions
      run: |
        cat suggestions.txt | while IFS= read -r suggestion; do
          gh pr comment ${{ github.event.pull_request.number }} --body "$suggestion"
        done

    - name: Check if Suggestions File Exists
      run: |
        if [ -f suggestions.txt ]; then
          echo "Suggestions file exists."
        else
          echo "Suggestions file does not exist."
        fi

    - name: Upload Suggestions Artifact
      uses: actions/upload-artifact@v3
      with:
        name: suggestions
        path: suggestions.txt

# This is a test comment to create a new commit on the test-github-action branch
# Adding a minor change to trigger the GitHub Action
